/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthFocusRouteImport } from './routes/_auth.focus'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthCreationLabsRouteImport } from './routes/_auth.creation-labs'
import { Route as AuthCreationLabRouteImport } from './routes/_auth.creation-lab'
import { Route as AuthCoursesRouteImport } from './routes/_auth.courses'
import { Route as AuthCommunityRouteImport } from './routes/_auth.community'
import { Route as ApiNotificationsTestRouteImport } from './routes/api/notifications/test'
import { Route as ApiJobsStudyPathRouteImport } from './routes/api/jobs/study-path'
import { Route as ApiJobsCourseOutlineRouteImport } from './routes/api/jobs/course-outline'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'
import { Route as ApiCommunityModerateRouteImport } from './routes/api/community/moderate'
import { Route as AuthCreationLabVideoRouteImport } from './routes/_auth.creation-lab.video'
import { Route as AuthCreationLabMultimediaEditorRouteImport } from './routes/_auth.creation-lab.multimedia-editor'
import { Route as AuthCreationLabHubRouteImport } from './routes/_auth.creation-lab.hub'
import { Route as AuthCreationLabCourseBuilderRouteImport } from './routes/_auth.creation-lab.course-builder'
import { Route as AuthCreationLabCertificateBuilderRouteImport } from './routes/_auth.creation-lab.certificate-builder'
import { Route as AuthCreationLabAudioRouteImport } from './routes/_auth.creation-lab.audio'
import { Route as ApiVideoStudioUploadsResumableRouteImport } from './routes/api/video-studio/uploads/resumable'
import { Route as ApiCertificatesVerifyCodeRouteImport } from './routes/api/certificates/verify.$code'
import { Route as ApiVideoStudioUploadsResumableUploadIdRouteImport } from './routes/api/video-studio/uploads/resumable.$uploadId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFocusRoute = AuthFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreationLabsRoute = AuthCreationLabsRouteImport.update({
  id: '/creation-labs',
  path: '/creation-labs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreationLabRoute = AuthCreationLabRouteImport.update({
  id: '/creation-lab',
  path: '/creation-lab',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoursesRoute = AuthCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCommunityRoute = AuthCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthRoute,
} as any)
const ApiNotificationsTestRoute = ApiNotificationsTestRouteImport.update({
  id: '/api/notifications/test',
  path: '/api/notifications/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsStudyPathRoute = ApiJobsStudyPathRouteImport.update({
  id: '/api/jobs/study-path',
  path: '/api/jobs/study-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsCourseOutlineRoute = ApiJobsCourseOutlineRouteImport.update({
  id: '/api/jobs/course-outline',
  path: '/api/jobs/course-outline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityModerateRoute = ApiCommunityModerateRouteImport.update({
  id: '/api/community/moderate',
  path: '/api/community/moderate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreationLabVideoRoute = AuthCreationLabVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AuthCreationLabRoute,
} as any)
const AuthCreationLabMultimediaEditorRoute =
  AuthCreationLabMultimediaEditorRouteImport.update({
    id: '/multimedia-editor',
    path: '/multimedia-editor',
    getParentRoute: () => AuthCreationLabRoute,
  } as any)
const AuthCreationLabHubRoute = AuthCreationLabHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthCreationLabRoute,
} as any)
const AuthCreationLabCourseBuilderRoute =
  AuthCreationLabCourseBuilderRouteImport.update({
    id: '/course-builder',
    path: '/course-builder',
    getParentRoute: () => AuthCreationLabRoute,
  } as any)
const AuthCreationLabCertificateBuilderRoute =
  AuthCreationLabCertificateBuilderRouteImport.update({
    id: '/certificate-builder',
    path: '/certificate-builder',
    getParentRoute: () => AuthCreationLabRoute,
  } as any)
const AuthCreationLabAudioRoute = AuthCreationLabAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => AuthCreationLabRoute,
} as any)
const ApiVideoStudioUploadsResumableRoute =
  ApiVideoStudioUploadsResumableRouteImport.update({
    id: '/api/video-studio/uploads/resumable',
    path: '/api/video-studio/uploads/resumable',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCertificatesVerifyCodeRoute =
  ApiCertificatesVerifyCodeRouteImport.update({
    id: '/api/certificates/verify/$code',
    path: '/api/certificates/verify/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVideoStudioUploadsResumableUploadIdRoute =
  ApiVideoStudioUploadsResumableUploadIdRouteImport.update({
    id: '/$uploadId',
    path: '/$uploadId',
    getParentRoute: () => ApiVideoStudioUploadsResumableRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/community': typeof AuthCommunityRoute
  '/courses': typeof AuthCoursesRoute
  '/creation-lab': typeof AuthCreationLabRouteWithChildren
  '/creation-labs': typeof AuthCreationLabsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/focus': typeof AuthFocusRoute
  '/profile': typeof AuthProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/creation-lab/audio': typeof AuthCreationLabAudioRoute
  '/creation-lab/certificate-builder': typeof AuthCreationLabCertificateBuilderRoute
  '/creation-lab/course-builder': typeof AuthCreationLabCourseBuilderRoute
  '/creation-lab/hub': typeof AuthCreationLabHubRoute
  '/creation-lab/multimedia-editor': typeof AuthCreationLabMultimediaEditorRoute
  '/creation-lab/video': typeof AuthCreationLabVideoRoute
  '/api/community/moderate': typeof ApiCommunityModerateRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/course-outline': typeof ApiJobsCourseOutlineRoute
  '/api/jobs/study-path': typeof ApiJobsStudyPathRoute
  '/api/notifications/test': typeof ApiNotificationsTestRoute
  '/api/certificates/verify/$code': typeof ApiCertificatesVerifyCodeRoute
  '/api/video-studio/uploads/resumable': typeof ApiVideoStudioUploadsResumableRouteWithChildren
  '/api/video-studio/uploads/resumable/$uploadId': typeof ApiVideoStudioUploadsResumableUploadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/community': typeof AuthCommunityRoute
  '/courses': typeof AuthCoursesRoute
  '/creation-lab': typeof AuthCreationLabRouteWithChildren
  '/creation-labs': typeof AuthCreationLabsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/focus': typeof AuthFocusRoute
  '/profile': typeof AuthProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/creation-lab/audio': typeof AuthCreationLabAudioRoute
  '/creation-lab/certificate-builder': typeof AuthCreationLabCertificateBuilderRoute
  '/creation-lab/course-builder': typeof AuthCreationLabCourseBuilderRoute
  '/creation-lab/hub': typeof AuthCreationLabHubRoute
  '/creation-lab/multimedia-editor': typeof AuthCreationLabMultimediaEditorRoute
  '/creation-lab/video': typeof AuthCreationLabVideoRoute
  '/api/community/moderate': typeof ApiCommunityModerateRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/course-outline': typeof ApiJobsCourseOutlineRoute
  '/api/jobs/study-path': typeof ApiJobsStudyPathRoute
  '/api/notifications/test': typeof ApiNotificationsTestRoute
  '/api/certificates/verify/$code': typeof ApiCertificatesVerifyCodeRoute
  '/api/video-studio/uploads/resumable': typeof ApiVideoStudioUploadsResumableRouteWithChildren
  '/api/video-studio/uploads/resumable/$uploadId': typeof ApiVideoStudioUploadsResumableUploadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/community': typeof AuthCommunityRoute
  '/_auth/courses': typeof AuthCoursesRoute
  '/_auth/creation-lab': typeof AuthCreationLabRouteWithChildren
  '/_auth/creation-labs': typeof AuthCreationLabsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/focus': typeof AuthFocusRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/creation-lab/audio': typeof AuthCreationLabAudioRoute
  '/_auth/creation-lab/certificate-builder': typeof AuthCreationLabCertificateBuilderRoute
  '/_auth/creation-lab/course-builder': typeof AuthCreationLabCourseBuilderRoute
  '/_auth/creation-lab/hub': typeof AuthCreationLabHubRoute
  '/_auth/creation-lab/multimedia-editor': typeof AuthCreationLabMultimediaEditorRoute
  '/_auth/creation-lab/video': typeof AuthCreationLabVideoRoute
  '/api/community/moderate': typeof ApiCommunityModerateRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/course-outline': typeof ApiJobsCourseOutlineRoute
  '/api/jobs/study-path': typeof ApiJobsStudyPathRoute
  '/api/notifications/test': typeof ApiNotificationsTestRoute
  '/api/certificates/verify/$code': typeof ApiCertificatesVerifyCodeRoute
  '/api/video-studio/uploads/resumable': typeof ApiVideoStudioUploadsResumableRouteWithChildren
  '/api/video-studio/uploads/resumable/$uploadId': typeof ApiVideoStudioUploadsResumableUploadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/community'
    | '/courses'
    | '/creation-lab'
    | '/creation-labs'
    | '/dashboard'
    | '/focus'
    | '/profile'
    | '/auth/callback'
    | '/creation-lab/audio'
    | '/creation-lab/certificate-builder'
    | '/creation-lab/course-builder'
    | '/creation-lab/hub'
    | '/creation-lab/multimedia-editor'
    | '/creation-lab/video'
    | '/api/community/moderate'
    | '/api/jobs/$id'
    | '/api/jobs/course-outline'
    | '/api/jobs/study-path'
    | '/api/notifications/test'
    | '/api/certificates/verify/$code'
    | '/api/video-studio/uploads/resumable'
    | '/api/video-studio/uploads/resumable/$uploadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/community'
    | '/courses'
    | '/creation-lab'
    | '/creation-labs'
    | '/dashboard'
    | '/focus'
    | '/profile'
    | '/auth/callback'
    | '/creation-lab/audio'
    | '/creation-lab/certificate-builder'
    | '/creation-lab/course-builder'
    | '/creation-lab/hub'
    | '/creation-lab/multimedia-editor'
    | '/creation-lab/video'
    | '/api/community/moderate'
    | '/api/jobs/$id'
    | '/api/jobs/course-outline'
    | '/api/jobs/study-path'
    | '/api/notifications/test'
    | '/api/certificates/verify/$code'
    | '/api/video-studio/uploads/resumable'
    | '/api/video-studio/uploads/resumable/$uploadId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/community'
    | '/_auth/courses'
    | '/_auth/creation-lab'
    | '/_auth/creation-labs'
    | '/_auth/dashboard'
    | '/_auth/focus'
    | '/_auth/profile'
    | '/auth/callback'
    | '/_auth/creation-lab/audio'
    | '/_auth/creation-lab/certificate-builder'
    | '/_auth/creation-lab/course-builder'
    | '/_auth/creation-lab/hub'
    | '/_auth/creation-lab/multimedia-editor'
    | '/_auth/creation-lab/video'
    | '/api/community/moderate'
    | '/api/jobs/$id'
    | '/api/jobs/course-outline'
    | '/api/jobs/study-path'
    | '/api/notifications/test'
    | '/api/certificates/verify/$code'
    | '/api/video-studio/uploads/resumable'
    | '/api/video-studio/uploads/resumable/$uploadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiCommunityModerateRoute: typeof ApiCommunityModerateRoute
  ApiJobsIdRoute: typeof ApiJobsIdRoute
  ApiJobsCourseOutlineRoute: typeof ApiJobsCourseOutlineRoute
  ApiJobsStudyPathRoute: typeof ApiJobsStudyPathRoute
  ApiNotificationsTestRoute: typeof ApiNotificationsTestRoute
  ApiCertificatesVerifyCodeRoute: typeof ApiCertificatesVerifyCodeRoute
  ApiVideoStudioUploadsResumableRoute: typeof ApiVideoStudioUploadsResumableRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/focus': {
      id: '/_auth/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthFocusRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/creation-labs': {
      id: '/_auth/creation-labs'
      path: '/creation-labs'
      fullPath: '/creation-labs'
      preLoaderRoute: typeof AuthCreationLabsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/creation-lab': {
      id: '/_auth/creation-lab'
      path: '/creation-lab'
      fullPath: '/creation-lab'
      preLoaderRoute: typeof AuthCreationLabRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses': {
      id: '/_auth/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthCoursesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/community': {
      id: '/_auth/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthCommunityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/notifications/test': {
      id: '/api/notifications/test'
      path: '/api/notifications/test'
      fullPath: '/api/notifications/test'
      preLoaderRoute: typeof ApiNotificationsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/study-path': {
      id: '/api/jobs/study-path'
      path: '/api/jobs/study-path'
      fullPath: '/api/jobs/study-path'
      preLoaderRoute: typeof ApiJobsStudyPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/course-outline': {
      id: '/api/jobs/course-outline'
      path: '/api/jobs/course-outline'
      fullPath: '/api/jobs/course-outline'
      preLoaderRoute: typeof ApiJobsCourseOutlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community/moderate': {
      id: '/api/community/moderate'
      path: '/api/community/moderate'
      fullPath: '/api/community/moderate'
      preLoaderRoute: typeof ApiCommunityModerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/creation-lab/video': {
      id: '/_auth/creation-lab/video'
      path: '/video'
      fullPath: '/creation-lab/video'
      preLoaderRoute: typeof AuthCreationLabVideoRouteImport
      parentRoute: typeof AuthCreationLabRoute
    }
    '/_auth/creation-lab/multimedia-editor': {
      id: '/_auth/creation-lab/multimedia-editor'
      path: '/multimedia-editor'
      fullPath: '/creation-lab/multimedia-editor'
      preLoaderRoute: typeof AuthCreationLabMultimediaEditorRouteImport
      parentRoute: typeof AuthCreationLabRoute
    }
    '/_auth/creation-lab/hub': {
      id: '/_auth/creation-lab/hub'
      path: '/hub'
      fullPath: '/creation-lab/hub'
      preLoaderRoute: typeof AuthCreationLabHubRouteImport
      parentRoute: typeof AuthCreationLabRoute
    }
    '/_auth/creation-lab/course-builder': {
      id: '/_auth/creation-lab/course-builder'
      path: '/course-builder'
      fullPath: '/creation-lab/course-builder'
      preLoaderRoute: typeof AuthCreationLabCourseBuilderRouteImport
      parentRoute: typeof AuthCreationLabRoute
    }
    '/_auth/creation-lab/certificate-builder': {
      id: '/_auth/creation-lab/certificate-builder'
      path: '/certificate-builder'
      fullPath: '/creation-lab/certificate-builder'
      preLoaderRoute: typeof AuthCreationLabCertificateBuilderRouteImport
      parentRoute: typeof AuthCreationLabRoute
    }
    '/_auth/creation-lab/audio': {
      id: '/_auth/creation-lab/audio'
      path: '/audio'
      fullPath: '/creation-lab/audio'
      preLoaderRoute: typeof AuthCreationLabAudioRouteImport
      parentRoute: typeof AuthCreationLabRoute
    }
    '/api/video-studio/uploads/resumable': {
      id: '/api/video-studio/uploads/resumable'
      path: '/api/video-studio/uploads/resumable'
      fullPath: '/api/video-studio/uploads/resumable'
      preLoaderRoute: typeof ApiVideoStudioUploadsResumableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificates/verify/$code': {
      id: '/api/certificates/verify/$code'
      path: '/api/certificates/verify/$code'
      fullPath: '/api/certificates/verify/$code'
      preLoaderRoute: typeof ApiCertificatesVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-studio/uploads/resumable/$uploadId': {
      id: '/api/video-studio/uploads/resumable/$uploadId'
      path: '/$uploadId'
      fullPath: '/api/video-studio/uploads/resumable/$uploadId'
      preLoaderRoute: typeof ApiVideoStudioUploadsResumableUploadIdRouteImport
      parentRoute: typeof ApiVideoStudioUploadsResumableRoute
    }
  }
}

interface AuthCreationLabRouteChildren {
  AuthCreationLabAudioRoute: typeof AuthCreationLabAudioRoute
  AuthCreationLabCertificateBuilderRoute: typeof AuthCreationLabCertificateBuilderRoute
  AuthCreationLabCourseBuilderRoute: typeof AuthCreationLabCourseBuilderRoute
  AuthCreationLabHubRoute: typeof AuthCreationLabHubRoute
  AuthCreationLabMultimediaEditorRoute: typeof AuthCreationLabMultimediaEditorRoute
  AuthCreationLabVideoRoute: typeof AuthCreationLabVideoRoute
}

const AuthCreationLabRouteChildren: AuthCreationLabRouteChildren = {
  AuthCreationLabAudioRoute: AuthCreationLabAudioRoute,
  AuthCreationLabCertificateBuilderRoute:
    AuthCreationLabCertificateBuilderRoute,
  AuthCreationLabCourseBuilderRoute: AuthCreationLabCourseBuilderRoute,
  AuthCreationLabHubRoute: AuthCreationLabHubRoute,
  AuthCreationLabMultimediaEditorRoute: AuthCreationLabMultimediaEditorRoute,
  AuthCreationLabVideoRoute: AuthCreationLabVideoRoute,
}

const AuthCreationLabRouteWithChildren = AuthCreationLabRoute._addFileChildren(
  AuthCreationLabRouteChildren,
)

interface AuthRouteChildren {
  AuthCommunityRoute: typeof AuthCommunityRoute
  AuthCoursesRoute: typeof AuthCoursesRoute
  AuthCreationLabRoute: typeof AuthCreationLabRouteWithChildren
  AuthCreationLabsRoute: typeof AuthCreationLabsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthFocusRoute: typeof AuthFocusRoute
  AuthProfileRoute: typeof AuthProfileRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCommunityRoute: AuthCommunityRoute,
  AuthCoursesRoute: AuthCoursesRoute,
  AuthCreationLabRoute: AuthCreationLabRouteWithChildren,
  AuthCreationLabsRoute: AuthCreationLabsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthFocusRoute: AuthFocusRoute,
  AuthProfileRoute: AuthProfileRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiVideoStudioUploadsResumableRouteChildren {
  ApiVideoStudioUploadsResumableUploadIdRoute: typeof ApiVideoStudioUploadsResumableUploadIdRoute
}

const ApiVideoStudioUploadsResumableRouteChildren: ApiVideoStudioUploadsResumableRouteChildren =
  {
    ApiVideoStudioUploadsResumableUploadIdRoute:
      ApiVideoStudioUploadsResumableUploadIdRoute,
  }

const ApiVideoStudioUploadsResumableRouteWithChildren =
  ApiVideoStudioUploadsResumableRoute._addFileChildren(
    ApiVideoStudioUploadsResumableRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiCommunityModerateRoute: ApiCommunityModerateRoute,
  ApiJobsIdRoute: ApiJobsIdRoute,
  ApiJobsCourseOutlineRoute: ApiJobsCourseOutlineRoute,
  ApiJobsStudyPathRoute: ApiJobsStudyPathRoute,
  ApiNotificationsTestRoute: ApiNotificationsTestRoute,
  ApiCertificatesVerifyCodeRoute: ApiCertificatesVerifyCodeRoute,
  ApiVideoStudioUploadsResumableRoute:
    ApiVideoStudioUploadsResumableRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
